AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Toponym API
Globals:
    Function:
        Timeout: 300
        MemorySize: 128
        Description: fastapi application around toponym
Resources:
    ToponymApiLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: toponym-api-lambda
            CodeUri: ./
            Handler: toponym_api.main.handler
            Runtime: python3.7
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ToponymApiRole
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: ToponymApiGateway
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api

    ToponymApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            OpenApiVersion: '3.0.0'
